### ISSUE TITLE
Instances

### ISSUE THREAD

**Issue by garyb** [robotlolita/puree#1]
One of the things that makes hierarchical packages particularly difficult to deal with currently is that instances are global, so even if you can work it out so that one package depends on a particular version of another, the instances will leak out and potentially result in overlapping instance definitions at a higher level.

Just thought this was worth raising as I didn't see it anywhere in the notes.

**Comment by joneshf** [comment]
Is this an intentional design decision on the ps side of things or an artifact of the way things are implemented?

**Comment by garyb** [comment]
It's intentional, copying the way Haskell works. Originally we didn't have this, but then there's quite a major disadvantage in that you have to explicitly import modules to get their instances, so for instance you can't do this:

``` haskell
module Main

main = do
  Debug.Trace.trace "hello"
  Debug.Trace.trace "world"
```

unless you import `Control.Monad.Eff`. Likewise instances aren't reachable transitively, so you end up with a whole lot of `import X ()` to make things work.

Maybe there is a better way though, as it seems class instances having this property really complicates attempts at modularity.

**Comment by joneshf** [comment]
Makes sense.

**Comment by robotlolita** [comment]
Ah, I overlooked this, but good point.
